update

diff --git a/bash_lib b/bash_lib
--- a/bash_lib
+++ b/bash_lib
@@ -3,90 +3,23 @@
 if [ "0" = "${bash_lib_included_flag:-0}" ]; then
     declare -x bash_lib_included_flag=bash_lib_included
 else
-    echo Warning, Double sourced!
+    echo "Warning, Double sourced!"
 fi
 
 shopt -s expand_aliases
 
 # define for test, due to the function LogPrint can not be multi-sourced
-#alias LogPrint='echo this is a test of alias;echo'
+# alias LogPrint='echo this is a test of alias;echo'
 alias LogPrint='echo'
+# alias LogPrint=':' # mute all display
+
 
 # TODO & Bug:
 # source this file multi-times, the global readonly definintion will issue errors (20170418)
 # random number generate function
-# pasuse function, read -n1 -r -p "Press any key to continue..." key
-    # read does this:
-    # user@host:~$ read -n1 -r -p "Press any key to continue..." key
-    # [...]
-    # user@host:~$ 
-    # The -n1 specifies that it only waits for a single character. The -r puts it into raw mode, which is necessary because otherwise, if you press something like backslash, it doesn't register until you hit the next key. The -p specifies the prompt, which must be quoted if it contains spaces. The key argument is only necessary if you want to know which key they pressed, in which case you can access it through $key.
-    # If you are using Bash, you can also specify a timeout with -t, which causes read to return a failure when a key isn't pressed. So for example:
-    # read -t5 -n1 -r -p 'Press any key in the next five seconds...' key
-    # if [ "$?" -eq "0" ]; then
-        # echo 'A key was pressed.'
-    # else
-        # echo 'No key was pressed.'
-    # fi
-            
-    # Strictly speaking, that would be "Enter any non-NUL character to continue". Some keys don't send any character (like Ctrl...) and some send more than one (like F1, Home...). bash ignores NUL characters.
-
-
-    # 100
-    # down vote
-    # I use a lot these ways that are very short, they are like @theunamedguy and @Jim solutions but with timeout and silent mode in addition.
-    # I especially love the last case and use it in a lot of script that run in loop until the user press Enter.
-
-    # Commands
-
-    # Enter solution
-    # read -rsp $'Press enter to continue...\n'
-    # Escape solution (with -d $'\e')
-    # read -rsp $'Press escape to continue...\n' -d $'\e'
-    # Any key solution (with -n 1)
-    # read -rsp $'Press any key to continue...\n' -n 1 key
-    # # echo $key
-    # Question with preselected choice (with -ei $'Y')
-    # read -rp $'Are you sure (Y/n) : ' -ei $'Y' key;
-    # # echo $key
-    # Timeout solution (with -t 5)
-    # read -rsp $'Press any key or wait 5 seconds to continue...\n' -n 1 -t 5;
-    # Sleep enhanced alias
-    # read -rst 0.5; timeout=$?
-    # # echo $timeout
-    # Explanation
-
-    # -r specifies raw mode, which don't allow combined characters like "\" or "^".
-
-    # -s specifies silent mode, and because we don't need keyboard output.
-
-    # -p $'prompt' specifies the prompt, which need to be between $' and ' to let spaces and escaped characters. Be careful, you must put between single quotes with dollars symbol to benefit escaped characters, otherwise you can use simple quotes.
-
-    # -d $'\e' specifies escappe as delimiter charater, so as a final character for current entry, this is possible to put any character but be careful to put a character that the user can type.
-
-    # -n 1 specifies that it only needs a single character.
-
-    # -e specifies readline mode.
-
-    # -i $'Y' specifies Y as initial text in readline mode.
-
-    # -t 5 specifies a timeout of 5 seconds
-
-    # key serve in case you need to know the input, in -n1 case, the key that has been pressed.
-
-    # $? serve to know the exit code of the last program, for read, 142 in case of timeout, 0 correct input. Put $? in a variable as soon as possible if you need to test it after somes commands, because all commands would rewrite $?
-    
-    # read -n1 is not portable. A portable way to do the same might be:
-
-    # (   trap "stty $(stty -g;stty -icanon)" EXIT
-    # LC_ALL=C dd bs=1 count=1 >/dev/null 2>&1
-    # )   </dev/tty
-    # Besides using  read, for just a press ENTER to continue prompt you could do:
-
-    # sed -n q </dev/tty
-
 # funny function like cowsay figlet
-# alias LogPrint=':' is this can mute all display ?
+# float number calcaulation
+# test the number bigger than 32767, what gona happen ?
 
 
 # Dependency :
@@ -94,7 +27,8 @@ alias LogPrint='echo'
 # Rules for bash_lib :
 # all the following functions and variables are used as libarary, so be careful with the implementation.
 # to avoid the name conflict, all the names, which will NOT be used by the caller,
-#     only used in this file should be started with the underline character.
+# those who only referenced in this file should be started with the underline.
+
 
 # Global definition
 
@@ -139,6 +73,97 @@ alias LogPrint='echo'
 ###
 ###     return 0
 ### }
+
+# for pause test
+# for var in 1 2 3;do echo ${var};pause;done
+function pause()
+{
+	SAVEDSTTY="$(stty -g)"
+	stty -echo
+	stty raw
+	dd if=/dev/tty bs=1 count=1 2>/dev/null
+	stty -raw
+	stty echo
+	stty $SAVEDSTTY
+  
+	# read does this:
+    # read -n1 -r -p "Press any key to continue..." key
+    # The -n1 specifies that it only waits for a single character. The -r puts it into raw mode, which is necessary because otherwise, if you press something like backslash, it doesn't register until you hit the next key. The -p specifies the prompt, which must be quoted if it contains spaces. The key argument is only necessary if you want to know which key they pressed, in which case you can access it through $key.
+    # If you are using Bash, you can also specify a timeout with -t, which causes read to return a failure when a key isn't pressed. So for example : 
+	# read -t5 -n1 -r -p 'Press any key in the next five seconds...' key
+    # if [ "$?" -eq "0" ]; then
+        # echo 'A key was pressed.'
+    # else
+        # echo 'No key was pressed.'
+    # fi 
+    # Strictly speaking, that would be "Enter any non-NUL character to continue". Some keys don't send any character (like Ctrl...) and some send more than one (like F1, Home...). bash ignores NUL characters.
+  
+    # -r specifies raw mode, which don't allow combined characters like "\" or "^".
+    # -s specifies silent mode, and because we don't need keyboard output.
+    # -p $'prompt' specifies the prompt, which need to be between $' and ' to let spaces and escaped characters. Be careful, you must put between single quotes with dollars symbol to benefit escaped characters, otherwise you can use simple quotes.
+    # Enter solution, read line, and mute the input char(s) display
+	# read -rsp $'Press enter to continue...\n'
+
+	# Escape solution
+	# -d $'\e' specifies escappe as delimiter charater, so as a final character for current entry, this is possible to put any character but be careful to put a character that the user can type.
+	# read -rsp $'Press escape to continue...\n' -d $'\e'
+
+	# Any key except Ctrl Shift Alt etc.
+	# -n 1 specifies that it only needs a single character.
+	# read -rsp $'Press any key to continue...\n' -n 1 key
+	# echo $key
+
+	# Question with preselected choice, -e specifies readline mode. -i $'Y' specifies Y as initial text in readline mode.
+	# -e specifies readline mode.
+	# -i $'Y' specifies Y as initial text in readline mode.
+	# key serve in case you need to know the input, in -n1 case, the key that has been pressed.
+	# read -rp $'Are you sure (Y/n) : ' -ei $'Y' key;
+	# echo $key
+
+	# Timeout solution
+	# -t 5 specifies a timeout of 5 seconds
+	# read -rsp $'Press any key or wait 2 seconds to continue...\n' -n 1 -t 2;
+	
+	# Sleep enhanced alias
+	# $? serve to know the exit code of the last program, for read, 142 in case of timeout, 0 correct input. Put $? in a variable as soon as possible if you need to test it after somes commands, because all commands would rewrite $?
+    # read -rst 3; timeout=$?
+    # echo $timeout
+	
+	# read -n1 is not portable. A portable way to do the same might be:
+    # (   trap "stty $(stty -g;stty -icanon)" EXIT
+    # LC_ALL=C dd bs=1 count=1 >/dev/null 2>&1
+    # )   </dev/tty
+    # Besides using read, for just a press ENTER to continue prompt you could do:
+    # sed -n q &>/dev/null </dev/tty
+
+	return 0
+}
+
+function GenRandomNum()
+{
+	local RandomNum=""
+	
+	
+	echo $RandomNum
+}
+
+# $1, length, if not, 8 chars ???
+function GenRandomString()
+{
+	local RandomString=""
+	
+	
+	echo $RandomString
+}
+
+# default, 8 letters(both upper case and lower case), digits, underline, other chars like $ ^ & etc.
+function GenRandomPsw()
+{
+	local RandomPsw=""
+	
+	
+	echo $RandomPsw
+}
 
 function _color_()
 {
@@ -372,6 +397,7 @@ function IsValidIP()
     return ${_returnValue}
 }
 
+# limitation : up to 10 digits seconds supported.
 # $1 seconds counting down
 # $2 display the number, default is display. no_display, disable the number display.
 function CountingDown()
